### PR TITLE
Updated character for USER@WORKSTATION from : to _

### PR DESCRIPTION
**Pull request by tiffanycmeyer13**
Windows didn't like the colon

### CODE REVIEW

**Comment by srcarter3** [comment]
Don't we want this on the specific windows branch? (Which probably doesn't exist yet, so you'll have to push it directly, without a PR...or push a copy of the main branch, and then open this PR)

**Comment by tiffanycmeyer13** [comment]
I thought we were going to change the symbol for all OS's so it was consistent?

**Comment by srcarter3** [comment]
Ah okay, I thought we were going to leave it just for Windows so it would be easier for us to troubleshoot which OS the users are coming from.
But I'm okay with changing it on all platforms...We just have to make sure it works on Linux before pushing it to the main branch though.

**Comment by tiffanycmeyer13** [comment]
Tested this on linux and the "_" works just fine.

**Pull request merged**
